In [1]:
import pandas as pd
import numpy as np

In [19]:
stuff = {'A':[1,2,3], 'B':[4,np.nan,6], 'C':[7,8,9], 'D':[10,11,12]}
df = pd.DataFrame(stuff)
df

   A    B  C   D
0  1  4.0  7  10
1  2  NaN  8  11
2  3  6.0  9  12

drop rows with null data

In [20]:
df.dropna(axis = 0)

   A    B  C   D
0  1  4.0  7  10
2  3  6.0  9  12

drop column with null data

In [21]:
df.dropna(axis = 1)

   A  C   D
0  1  7  10
1  2  8  11
2  3  9  12

In [22]:
# not permanent, inplace = false
df

   A    B  C   D
0  1  4.0  7  10
1  2  NaN  8  11
2  3  6.0  9  12

more then one? set threshold

In [17]:
df.dropna(thresh=2, axis = 1)

   A  C   D
0  1  7  10
1  2  8  11
2  3  9  12

replace with fillna()

In [23]:
df.fillna(value=40)

   A     B  C   D
0  1   4.0  7  10
1  2  40.0  8  11
2  3   6.0  9  12

using math function

In [24]:
#avg
df.fillna(value=df['B'].mean())

   A    B  C   D
0  1  4.0  7  10
1  2  5.0  8  11
2  3  6.0  9  12

In [25]:
#max
df.fillna(value=df['B'].max())

   A    B  C   D
0  1  4.0  7  10
1  2  6.0  8  11
2  3  6.0  9  12

In [26]:
#min
df.fillna(value=df['B'].min())

   A    B  C   D
0  1  4.0  7  10
1  2  4.0  8  11
2  3  6.0  9  12

In [27]:
#sum
df.fillna(value=df['B'].sum())

   A     B  C   D
0  1   4.0  7  10
1  2  10.0  8  11
2  3   6.0  9  12