In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dog_data_short.csv')
df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

adding column

In [4]:
gender = ["Male", "Female", "Male", "Male", "Female"]
df["Gender"] = gender
df

                 Breed        Color  DogName  OwnerZip  Gender
0             COCKAPOO        BROWN  CHARLEY     15236    Male
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238  Female
2        BELG MALINOIS      BRINDLE     EICH     15238    Male
3                MIXED  BLACK/BROWN    ARROW     15104    Male
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139  Female

remove column

In [ ]:
df.drop("Gender", axis=1, inplace=True) # for column removing axis is 1

KeyError: "['Gender'] not found in axis"

In [10]:
df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

removing row

In [ ]:
df.drop(3, axis = 0, inplace=True) # for row removing axis is 0

In [16]:
df.drop(3, axis = 0, inplace=True) # for row removing axis is 0

In [17]:
df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139