In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('dog_data_short.csv')
df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

create a new column

In [13]:
df['Frame Header'] = ['Dog1', 'Dog2', 'Dog3', 'Dog4', 'Dog5']
df

                 Breed        Color  DogName  OwnerZip Frame Header
0             COCKAPOO        BROWN  CHARLEY     15236         Dog1
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238         Dog2
2        BELG MALINOIS      BRINDLE     EICH     15238         Dog3
3                MIXED  BLACK/BROWN    ARROW     15104         Dog4
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139         Dog5

set index

In [14]:
df.set_index("Frame Header", inplace=True)

In [15]:
df

                            Breed        Color  DogName  OwnerZip
Frame Header
Dog1                     COCKAPOO        BROWN  CHARLEY     15236
Dog2                 GER SHEPHERD  BLACK/BROWN   TACODA     15238
Dog3                BELG MALINOIS      BRINDLE     EICH     15238
Dog4                        MIXED  BLACK/BROWN    ARROW     15104
Dog5          AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

reset index

In [16]:
df.reset_index(inplace=True)

In [17]:
df

  Frame Header                Breed        Color  DogName  OwnerZip
0         Dog1             COCKAPOO        BROWN  CHARLEY     15236
1         Dog2         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2         Dog3        BELG MALINOIS      BRINDLE     EICH     15238
3         Dog4                MIXED  BLACK/BROWN    ARROW     15104
4         Dog5  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

drop column

In [18]:
df.drop('Frame Header', axis=1, inplace=True)  # for column removing axis is 1

In [19]:
df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [20]:
df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139