In [1]:
import pandas as pd
import numpy as np

In [21]:
stuff = {
    'Corporation':['Apple', 'Google', 'Meta', 'Apple', 'Google','Meta'],
    'Employees':['John', 'April', 'Wes', 'Beth', 'Justin', 'Steph'],
    'Salary':[200, 220, 190, 130, 120, 150],
}
df = pd.DataFrame(stuff)
df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

**create function**

In [22]:
def times1000(x):
    return format(x * 1000, ',d')
df['Salary'].apply(times1000)

0    200,000
1    220,000
2    190,000
3    130,000
4    120,000
5    150,000
Name: Salary, dtype: str

**Append to the current dataframe**

In [23]:
df["Salary"] = df["Salary"].apply(times1000)
df

  Corporation Employees   Salary
0       Apple      John  200,000
1      Google     April  220,000
2        Meta       Wes  190,000
3       Apple      Beth  130,000
4      Google    Justin  120,000
5        Meta     Steph  150,000

**Fnction on multiple column**

In [24]:
def namer(x):
    return 'RAMIM: ' + x

# apply to two columns
df[['Corporation', 'Employees']].apply(namer)

     Corporation      Employees
0   RAMIM: Apple    RAMIM: John
1  RAMIM: Google   RAMIM: April
2    RAMIM: Meta     RAMIM: Wes
3   RAMIM: Apple    RAMIM: Beth
4  RAMIM: Google  RAMIM: Justin
5    RAMIM: Meta   RAMIM: Steph

**Append to the current DataFrame**

In [25]:
df[['Corporation', 'Employees']] = df[['Corporation', 'Employees']].apply(namer)
df

     Corporation      Employees   Salary
0   RAMIM: Apple    RAMIM: John  200,000
1  RAMIM: Google   RAMIM: April  220,000
2    RAMIM: Meta     RAMIM: Wes  190,000
3   RAMIM: Apple    RAMIM: Beth  130,000
4  RAMIM: Google  RAMIM: Justin  120,000
5    RAMIM: Meta   RAMIM: Steph  150,000

In [26]:
df

     Corporation      Employees   Salary
0   RAMIM: Apple    RAMIM: John  200,000
1  RAMIM: Google   RAMIM: April  220,000
2    RAMIM: Meta     RAMIM: Wes  190,000
3   RAMIM: Apple    RAMIM: Beth  130,000
4  RAMIM: Google  RAMIM: Justin  120,000
5    RAMIM: Meta   RAMIM: Steph  150,000