In [1]:
import numpy as np
import pandas as pd

import csv file

In [2]:
my_df = pd.read_csv('dog_data_short.csv')
my_df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

adding column from the list

In [12]:
gender = ["Male", "Female", "Male", "Male", "Female"]
my_df['Gender'] = gender
my_df

                 Breed        Color  DogName  OwnerZip  Gender  Alive/Dead
0             COCKAPOO        BROWN  CHARLEY     15236    Male        True
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238  Female        True
2        BELG MALINOIS      BRINDLE     EICH     15238    Male        True
3                MIXED  BLACK/BROWN    ARROW     15104    Male        True
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139  Female        True

adding default values

In [13]:
my_df["Alive/Dead"] = [True]*len(my_df)
my_df

                 Breed        Color  DogName  OwnerZip  Gender  Alive/Dead
0             COCKAPOO        BROWN  CHARLEY     15236    Male        True
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238  Female        True
2        BELG MALINOIS      BRINDLE     EICH     15238    Male        True
3                MIXED  BLACK/BROWN    ARROW     15104    Male        True
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139  Female        True

adding NaN values

In [14]:
my_df["Show Dog"] = [np.nan]*len(my_df)
my_df

,Breed,Color,DogName,OwnerZip,Gender,Alive/Dead,Show Dog
0,COCKAPOO,BROWN,CHARLEY,15236,Male,True,NaN
1,GER SHEPHERD,BLACK/BROWN,TACODA,15238,Female,True,NaN
2,BELG MALINOIS,BRINDLE,EICH,15238,Male,True,NaN
3,MIXED,BLACK/BROWN,ARROW,15104,Male,True,NaN
4,AM PIT BULL TERRIER,WHITE/BROWN,OAKLEY,15139,Female,True,NaN

adding columns with .insert() - Allows Position

In [17]:
my_df.insert(1, "Adopted", [True]*len(my_df), True)
my_df

,Breed,Adopted,Adopted,Color,DogName,OwnerZip,Gender,Alive/Dead,Show Dog
0,COCKAPOO,True,True,BROWN,CHARLEY,15236,Male,True,NaN
1,GER SHEPHERD,True,True,BLACK/BROWN,TACODA,15238,Female,True,NaN
2,BELG MALINOIS,True,True,BRINDLE,EICH,15238,Male,True,NaN
3,MIXED,True,True,BLACK/BROWN,ARROW,15104,Male,True,NaN
4,AM PIT BULL TERRIER,True,True,WHITE/BROWN,OAKLEY,15139,Female,True,NaN

adding column with .assign() - creates new df

In [19]:
my_df2 = my_df.assign(Horse = [False]*len(my_df))
my_df2

,Breed,Adopted,Adopted,Color,DogName,OwnerZip,Gender,Alive/Dead,Show Dog,Horse
0,COCKAPOO,True,True,BROWN,CHARLEY,15236,Male,True,NaN,False
1,GER SHEPHERD,True,True,BLACK/BROWN,TACODA,15238,Female,True,NaN,False
2,BELG MALINOIS,True,True,BRINDLE,EICH,15238,Male,True,NaN,False
3,MIXED,True,True,BLACK/BROWN,ARROW,15104,Male,True,NaN,False
4,AM PIT BULL TERRIER,True,True,WHITE/BROWN,OAKLEY,15139,Female,True,NaN,False

In [20]:
my_df

,Breed,Adopted,Adopted,Color,DogName,OwnerZip,Gender,Alive/Dead,Show Dog
0,COCKAPOO,True,True,BROWN,CHARLEY,15236,Male,True,NaN
1,GER SHEPHERD,True,True,BLACK/BROWN,TACODA,15238,Female,True,NaN
2,BELG MALINOIS,True,True,BRINDLE,EICH,15238,Male,True,NaN
3,MIXED,True,True,BLACK/BROWN,ARROW,15104,Male,True,NaN
4,AM PIT BULL TERRIER,True,True,WHITE/BROWN,OAKLEY,15139,Female,True,NaN