In [1]:
import pandas as pd
import numpy as np

In [2]:
stuff = {
    'Corporation':['Apple', 'Google', 'Meta', 'Apple', 'Google','Meta'],
    'Employees':['John', 'April', 'Wes', 'Beth', 'Justin', 'Steph'],
    'Salary':[200, 220, 190, 130, 120, 150],
}
df = pd.DataFrame(stuff)
df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

**Sort salarys from lowest to highest**

In [3]:
df.sort_values('Salary')

  Corporation Employees  Salary
4      Google    Justin     120
3       Apple      Beth     130
5        Meta     Steph     150
2        Meta       Wes     190
0       Apple      John     200
1      Google     April     220

**Sort salarys from highest to lowest**

In [4]:
df.sort_values('Salary', ascending=False)

  Corporation Employees  Salary
1      Google     April     220
0       Apple      John     200
2        Meta       Wes     190
5        Meta     Steph     150
3       Apple      Beth     130
4      Google    Justin     120

In [6]:
# not permanent cuz inplace is not True
df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

In [8]:
# inplace = True
df.sort_values('Salary', ascending=False, inplace=True)
df

  Corporation Employees  Salary
1      Google     April     220
0       Apple      John     200
2        Meta       Wes     190
5        Meta     Steph     150
3       Apple      Beth     130
4      Google    Justin     120

In [9]:
df

  Corporation Employees  Salary
1      Google     April     220
0       Apple      John     200
2        Meta       Wes     190
5        Meta     Steph     150
3       Apple      Beth     130
4      Google    Justin     120

**Sort string Alphabetically**

In [11]:
df.sort_values('Corporation', ascending=True)

  Corporation Employees  Salary
0       Apple      John     200
3       Apple      Beth     130
1      Google     April     220
4      Google    Justin     120
2        Meta       Wes     190
5        Meta     Steph     150

**Sorting string Alphabetically - Descending**

In [12]:
df.sort_values('Corporation', ascending=False)

  Corporation Employees  Salary
2        Meta       Wes     190
5        Meta     Steph     150
1      Google     April     220
4      Google    Justin     120
0       Apple      John     200
3       Apple      Beth     130