In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dog_data.csv')
df

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

grab a specific column

In [3]:
df['DogName']

0             CHARLEY
1              TACODA
2                EICH
3               ARROW
4              OAKLEY
            ...
2665          WINSLOW
2666    ROCKY KALAKOS
2667            ELLIE
2668         CLARENCE
2669          GRIFFIN
Name: DogName, Length: 2670, dtype: str

count value

In [7]:
df1 = df['DogName'].value_counts()
df1

DogName
LUCY             35
BELLA            30
BAILEY           29
BUDDY            29
DAISY            26
                 ..
NINO              1
WINSLOW           1
ROCKY KALAKOS     1
CLARENCE          1
GRIFFIN           1
Name: count, Length: 1428, dtype: int64

In [10]:
df2 = pd.DataFrame(df1).head(10)
df2

         count
DogName
LUCY        35
BELLA       30
BAILEY      29
BUDDY       29
DAISY       26
MOLLY       23
MAX         22
SADIE       20
CHARLIE     18
TOBY        17

grab uniques

In [16]:
df3 = df['DogName'].unique()
df3

<StringArray>
[          'CHARLEY',            'TACODA',              'EICH',
             'ARROW',            'OAKLEY',            'BAILEY',
 'MIMI PEARL FOSTER',             'LEROI',        'ZOE VITSAS',
             'TAFFY',
 ...
             'ASPEN',            'WESTIN',              'LOKI',
             'BULLA',             'MARGE',              'NINO',
           'WINSLOW',     'ROCKY KALAKOS',          'CLARENCE',
           'GRIFFIN']
Length: 1429, dtype: str

In [18]:
df4 = pd.DataFrame(df3)
df4

                  0
0           CHARLEY
1            TACODA
2              EICH
3             ARROW
4            OAKLEY
...             ...
1424           NINO
1425        WINSLOW
1426  ROCKY KALAKOS
1427       CLARENCE
1428        GRIFFIN

[1429 rows x 1 columns]

In [25]:
df5 = df4.rename(columns={0: 'Dogish Bro'}).head(30)
df5

           Dogish Bro
0             CHARLEY
1              TACODA
2                EICH
3               ARROW
4              OAKLEY
5              BAILEY
6   MIMI PEARL FOSTER
7               LEROI
8          ZOE VITSAS
9               TAFFY
10               DUDE
11            CHICKIE
12               KING
13              EMILY
14              ELLIE
15              RUSTY
16                NaN
17             JUILET
18              ROMEO
19               LOLA
20                ABE
21             MAGGIE
22              BUDDY
23           PRINCESS
24   CHRISTINA "TINA"
25              HOWIE
26              HAPPY
27              LILLY
28             SHADOE
29              SABLE