In [1]:
import pandas as pd
import numpy as np

In [2]:
stuff = {
    'Corporation':['Apple', 'Google', 'Meta', 'Apple', 'Google','Meta'],
    'Employees':['John', 'April', 'Wes', 'Beth', 'Justin', 'Steph'],
    'Salary':[200, 220, 190, 130, 120, 150]}
df = pd.DataFrame(stuff)
df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

create function

In [3]:
def times1000(x):
    return format(x * 1000, ',d')

using apply function

In [4]:
df['Salary'].apply(times1000)

0    200,000
1    220,000
2    190,000
3    130,000
4    120,000
5    150,000
Name: Salary, dtype: str

In [5]:
pd.DataFrame(df['Salary'].apply(times1000))

    Salary
0  200,000
1  220,000
2  190,000
3  130,000
4  120,000
5  150,000

add Elder as Last name

In [10]:
def namer(x):
    if x == 'John': 
        return 'John Elder'
    else:
        return x

use apply function

In [11]:
df['Employees'].apply(namer)

0    John Elder
1         April
2           Wes
3          Beth
4        Justin
5         Steph
Name: Employees, dtype: str

In [12]:
pd.DataFrame(df['Employees'].apply(namer))

    Employees
0  John Elder
1       April
2         Wes
3        Beth
4      Justin
5       Steph

Use Lambda

In [13]:
df['Salary'].apply(lambda x: format(x * 1000, ',d'))

0    200,000
1    220,000
2    190,000
3    130,000
4    120,000
5    150,000
Name: Salary, dtype: str

In [14]:
pd.DataFrame(df['Salary'].apply(lambda x: format(x * 1000, ',d')))

    Salary
0  200,000
1  220,000
2  190,000
3  130,000
4  120,000
5  150,000