In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dog_data_short.csv')
df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [4]:
df.index = ["A", "B", "C", "D", "E"]
df

                 Breed        Color  DogName  OwnerZip
A             COCKAPOO        BROWN  CHARLEY     15236
B         GER SHEPHERD  BLACK/BROWN   TACODA     15238
C        BELG MALINOIS      BRINDLE     EICH     15238
D                MIXED  BLACK/BROWN    ARROW     15104
E  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

method 1: grab row location

In [5]:
df.loc["B"]

Breed       GER SHEPHERD
Color        BLACK/BROWN
DogName           TACODA
OwnerZip           15238
Name: B, dtype: object

method 2: grab row index location

In [6]:
df.iloc[1]

Breed       GER SHEPHERD
Color        BLACK/BROWN
DogName           TACODA
OwnerZip           15238
Name: B, dtype: object

specific points(row and column)

In [7]:
# df.loc['Row', 'col']
df.loc["C", "DogName"]

'EICH'

subset

In [9]:
# df.loc[['row', 'row'],['col', 'col']]
df.loc[['B', 'C'],['Breed', 'DogName']]

           Breed DogName
B   GER SHEPHERD  TACODA
C  BELG MALINOIS    EICH