In [1]:
import pandas as pd
import numpy as np

In [3]:
my_df = pd.read_csv('dog_data.csv')
my_df

                  Breed        Color            DogName  OwnerZip
0              COCKAPOO        BROWN            CHARLEY   15236.0
1          GER SHEPHERD  BLACK/BROWN             TACODA   15238.0
2         BELG MALINOIS      BRINDLE               EICH   15238.0
3                 MIXED  BLACK/BROWN              ARROW   15104.0
4   AM PIT BULL TERRIER  WHITE/BROWN             OAKLEY   15139.0
5      SCOTTISH TERRIER        BLACK             BAILEY   15129.0
6     YORKSHIRE TERRIER    BLACK/TAN  MIMI PEARL FOSTER   15090.0
7         DACHSHUND MIX  WHITE/BROWN              LEROI   15101.0
8     SHETLAND SHEEPDOG  WHITE/BROWN         ZOE VITSAS   15238.0
9    LABRADOR RETRIEVER       YELLOW              TAFFY   15228.0
10         BICHON FRISE        WHITE               DUDE   15238.0
11       LHASA APSO MIX  WHITE/BROWN            CHICKIE   15238.0
12     AM PITT BULL MIX        BROWN               KING   15235.0
13     AM PITT BULL MIX        WHITE              EMILY   15108.0
14     BRITTANY SPANIEL  WHITE/BROWN              ELLIE   15228.0
15                MIXED        WHITE              RUSTY   15120.0
16          TERRIER MIX      SPOTTED              ANNIE   15239.0
17       COCKER SPANIEL       BLONDE             JUILET       NaN
18       COCKER SPANIEL        BLACK              ROMEO   15214.0

grab firs five rows

In [5]:
my_df.head()

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY   15236.0
1         GER SHEPHERD  BLACK/BROWN   TACODA   15238.0
2        BELG MALINOIS      BRINDLE     EICH   15238.0
3                MIXED  BLACK/BROWN    ARROW   15104.0
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY   15139.0

grab certain number of first rows

In [7]:
my_df.head(9)

                 Breed        Color            DogName  OwnerZip
0             COCKAPOO        BROWN            CHARLEY   15236.0
1         GER SHEPHERD  BLACK/BROWN             TACODA   15238.0
2        BELG MALINOIS      BRINDLE               EICH   15238.0
3                MIXED  BLACK/BROWN              ARROW   15104.0
4  AM PIT BULL TERRIER  WHITE/BROWN             OAKLEY   15139.0
5     SCOTTISH TERRIER        BLACK             BAILEY   15129.0
6    YORKSHIRE TERRIER    BLACK/TAN  MIMI PEARL FOSTER   15090.0
7        DACHSHUND MIX  WHITE/BROWN              LEROI   15101.0
8    SHETLAND SHEEPDOG  WHITE/BROWN         ZOE VITSAS   15238.0

grab last five rows

In [8]:
my_df.tail()

               Breed        Color DogName  OwnerZip
14  BRITTANY SPANIEL  WHITE/BROWN   ELLIE   15228.0
15             MIXED        WHITE   RUSTY   15120.0
16       TERRIER MIX      SPOTTED   ANNIE   15239.0
17    COCKER SPANIEL       BLONDE  JUILET       NaN
18    COCKER SPANIEL        BLACK   ROMEO   15214.0

grab certain number of last rows

In [9]:
my_df.tail(8)

               Breed        Color  DogName  OwnerZip
11    LHASA APSO MIX  WHITE/BROWN  CHICKIE   15238.0
12  AM PITT BULL MIX        BROWN     KING   15235.0
13  AM PITT BULL MIX        WHITE    EMILY   15108.0
14  BRITTANY SPANIEL  WHITE/BROWN    ELLIE   15228.0
15             MIXED        WHITE    RUSTY   15120.0
16       TERRIER MIX      SPOTTED    ANNIE   15239.0
17    COCKER SPANIEL       BLONDE   JUILET       NaN
18    COCKER SPANIEL        BLACK    ROMEO   15214.0

get info about the dataFrame

In [10]:
my_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Breed     19 non-null     str
 1   Color     19 non-null     str
 2   DogName   19 non-null     str
 3   OwnerZip  18 non-null     float64
dtypes: float64(1), str(3)
memory usage: 740.0 bytes

get shape of rows and columns

In [11]:
my_df.shape

(19, 4)

get the number of dimension

In [12]:
my_df.ndim

2

get the column datatype

In [13]:
my_df.dtypes

Breed           str
Color           str
DogName         str
OwnerZip    float64
dtype: object

get some statistics about the data

In [14]:
my_df.describe()

           OwnerZip
count     18.000000
mean   15186.722222
std       61.642046
min    15090.000000
25%    15122.250000
50%    15228.000000
75%    15238.000000
max    15239.000000

describe a specific coumn

In [15]:
my_df['Breed'].describe()

count        19
unique       16
top       MIXED
freq          2
Name: Breed, dtype: object

In [16]:
my_df['Color'].describe()

count              19
unique             10
top       WHITE/BROWN
freq                5
Name: Color, dtype: object

In [17]:
my_df['DogName'].describe()

count          19
unique         19
top       CHARLEY
freq            1
Name: DogName, dtype: object

select specific column using brackets

In [18]:
my_df["Breed"]

0                COCKAPOO
1            GER SHEPHERD
2           BELG MALINOIS
3                   MIXED
4     AM PIT BULL TERRIER
5        SCOTTISH TERRIER
6       YORKSHIRE TERRIER
7           DACHSHUND MIX
8       SHETLAND SHEEPDOG
9      LABRADOR RETRIEVER
10           BICHON FRISE
11         LHASA APSO MIX
12       AM PITT BULL MIX
13       AM PITT BULL MIX
14       BRITTANY SPANIEL
15                  MIXED
16            TERRIER MIX
17         COCKER SPANIEL
18         COCKER SPANIEL
Name: Breed, dtype: str

select specific column using dot notation

In [19]:
my_df.Breed

0                COCKAPOO
1            GER SHEPHERD
2           BELG MALINOIS
3                   MIXED
4     AM PIT BULL TERRIER
5        SCOTTISH TERRIER
6       YORKSHIRE TERRIER
7           DACHSHUND MIX
8       SHETLAND SHEEPDOG
9      LABRADOR RETRIEVER
10           BICHON FRISE
11         LHASA APSO MIX
12       AM PITT BULL MIX
13       AM PITT BULL MIX
14       BRITTANY SPANIEL
15                  MIXED
16            TERRIER MIX
17         COCKER SPANIEL
18         COCKER SPANIEL
Name: Breed, dtype: str

select specific column using location

In [ ]:
my_df.iloc[:,0] # rows start:end , starting column

2           BELG MALINOIS
3                   MIXED
4     AM PIT BULL TERRIER
5        SCOTTISH TERRIER
6       YORKSHIRE TERRIER
7           DACHSHUND MIX
8       SHETLAND SHEEPDOG
9      LABRADOR RETRIEVER
10           BICHON FRISE
11         LHASA APSO MIX
12       AM PITT BULL MIX
13       AM PITT BULL MIX
14       BRITTANY SPANIEL
15                  MIXED
16            TERRIER MIX
17         COCKER SPANIEL
18         COCKER SPANIEL
Name: Breed, dtype: str

In [26]:
my_df.iloc[5:10,2]

5               BAILEY
6    MIMI PEARL FOSTER
7                LEROI
8           ZOE VITSAS
9                TAFFY
Name: DogName, dtype: str